; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27049.0 

	TITLE	D:\_HP_Stream\__NLU_Notes\__Work_In_Progress\__Halt_Decider_X86\___x86utm_VS\Prior_Versions\2023_03_02\Halt7.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_BEGIN
PUBLIC	_Heap_PTR
PUBLIC	_Heap_END
PUBLIC	_END
_DATA	SEGMENT
_BEGIN	DB	'BEGIN STATIC DATA', 00H
	ORG $+2
_Heap_PTR DD	011111111H
_Heap_END DD	022222222H
_END	DB	'END STATIC DATA', 00H
_DATA	ENDS
PUBLIC	_OutputString
PUBLIC	_Output
PUBLIC	_Allocate
PUBLIC	_SaveState
PUBLIC	_LoadState
PUBLIC	_DebugStep
PUBLIC	_PushBack
PUBLIC	_StackPush
PUBLIC	_get_code_end
PUBLIC	_Last_Address_Of_Operating_System
PUBLIC	_Output_Decoded
PUBLIC	_CopyMachineCode
PUBLIC	_Infinite_Loop_Needs_To_Be_Aborted_Trace
PUBLIC	_Infinite_Recursion_Needs_To_Be_Aborted_Trace
PUBLIC	_Infinite_Simulation_Needs_To_Be_Aborted_Trace0
PUBLIC	_Needs_To_Be_Aborted0
PUBLIC	_Decide_Halting0
PUBLIC	_Init_slave_state0
PUBLIC	_Infinite_Simulation_Needs_To_Be_Aborted_Trace
PUBLIC	_Needs_To_Be_Aborted
PUBLIC	_Decide_Halting
PUBLIC	_Init_slave_state
PUBLIC	_Needs_To_Be_Aborted_Trace_HH
PUBLIC	_Needs_To_Be_Aborted_HH
PUBLIC	_Decide_Halting_HH
PUBLIC	_Init_Halts_HH
PUBLIC	_HH
PUBLIC	_H1
PUBLIC	_H
PUBLIC	_Sipser_H
PUBLIC	_Kozen_K
PUBLIC	_H0
PUBLIC	_T
PUBLIC	_Halts
PUBLIC	_Infinite_Loop2
PUBLIC	_Infinite_Loop3
PUBLIC	_Add3
PUBLIC	_HR
PUBLIC	_PR
PUBLIC	_Simulate
PUBLIC	_Py
PUBLIC	_Pz
PUBLIC	_Px
PUBLIC	_Sipser_D
PUBLIC	_Strachey_P
PUBLIC	_Kozen_N
PUBLIC	_PP
PUBLIC	_P
PUBLIC	_E
PUBLIC	_DD
PUBLIC	_D
PUBLIC	_Infinite_Recursion
PUBLIC	_Infinite_Loop
PUBLIC	_main
_DATA	SEGMENT
$SG9419	DB	'source[N]: ', 00H
$SG9420	DB	'CopyMachineCode destination[-1]: ', 00H
	ORG $+2
$SG9421	DB	'CopyMachineCode destination[-2]: ', 00H
	ORG $+2
$SG9542	DB	'Infinite Loop Detected Simulation Stopped', 0aH, 0aH, 00H
$SG9544	DB	'Infinite Recursion Detected Simulation Stopped', 0aH, 0aH
	DB	00H
	ORG $+3
$SG9546	DB	'Infinitely Recursive Simulation Detected Simulation Stop'
	DB	'ped', 0aH, 0aH, 00H
	ORG $+2
$SG9645	DB	'Infinite Loop Detected Simulation Stopped', 0aH, 0aH, 00H
$SG9647	DB	'Infinite Recursion Detected Simulation Stopped', 0aH, 0aH
	DB	00H
	ORG $+3
$SG9649	DB	'Infinitely Recursive Simulation Detected Simulation Stop'
	DB	'ped', 0aH, 0aH, 00H
	ORG $+2
$SG9687	DB	'Local Halt Decider: Infinite Loop Detected Simulation St'
	DB	'opped', 0aH, 0aH, 00H
$SG9693	DB	'Local Halt Decider: Infinite Recursion Detected Simulati'
	DB	'on Stopped', 0aH, 0aH, 00H
	ORG $+3
$SG9773	DB	'New slave_stack at:', 00H
$SG9832	DB	0aH, 'H1: Begin Simulation   Execution Trace Stored at:', 00H
	ORG $+1
$SG9775	DB	0aH, 'Begin Local Halt Decider Simulation   Execution Tra'
	DB	'ce Stored at:', 00H
	ORG $+2
$SG9833	DB	'Address_of_H1:', 00H
	ORG $+1
$SG9835	DB	'H1: ', 00H
	ORG $+3
$SG9836	DB	'H1: End Simulation   Input Terminated Normally', 0aH, 0aH
	DB	00H
	ORG $+3
$SG9870	DB	0aH, 'H: Begin Simulation   Execution Trace Stored at:', 00H
	ORG $+2
$SG9871	DB	'Address_of_H:', 00H
	ORG $+2
$SG9873	DB	'H: ', 00H
$SG9874	DB	'H: End Simulation   Input Terminated Normally', 0aH, 0aH
	DB	00H
$SG9908	DB	0aH, 'Sipser_H: Begin Simulation   Execution Trace Stored'
	DB	' at:', 00H
	ORG $+3
$SG9909	DB	'Address_of_Sipser_H:', 00H
	ORG $+3
$SG9911	DB	'Sipser_H: ', 00H
	ORG $+1
$SG9912	DB	'Sipser_H: End Simulation   Input Terminated Normally', 0aH
	DB	0aH, 00H
	ORG $+1
$SG9946	DB	0aH, 'H: Begin Simulation   Execution Trace Stored at:', 00H
	ORG $+2
$SG9947	DB	'Address_of_Kozen_K:', 00H
$SG9949	DB	'Kozen_K: ', 00H
	ORG $+2
$SG9950	DB	'Kozen_K: End Simulation   Input Terminated Normally', 0aH
	DB	0aH, 00H
	ORG $+2
$SG9977	DB	0aH, 'H0: Begin Simulation   Execution Trace Stored at:', 00H
	ORG $+1
$SG9978	DB	'Address_of_H0:', 00H
	ORG $+1
$SG9980	DB	'H0: ', 00H
	ORG $+3
$SG9981	DB	'H: End Simulation   Input Terminated Normally', 0aH, 0aH
	DB	00H
$SG10008 DB	0aH, 'T: Begin Simulation   Execution Trace Stored at:', 00H
	ORG $+2
$SG10009 DB	'Address_of_T:', 00H
	ORG $+2
$SG10011 DB	'T: ', 00H
$SG10012 DB	'H: End Simulation   Input Terminated Normally', 0aH, 0aH
	DB	00H
$SG10122 DB	'Input_Halts = ', 00H
_DATA	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 954
	push	ebp
	mov	ebp, esp
; Line 955
	push	OFFSET _DD
	push	OFFSET _DD
	call	_HH
	add	esp, 8
	push	eax
	push	OFFSET $SG10122
	call	_Output
	add	esp, 8
; Line 979
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Infinite_Loop PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 949
	push	ebp
	mov	ebp, esp
$HERE$3:
; Line 950
	jmp	SHORT $HERE$3
; Line 951
	pop	ebp
	ret	0
_Infinite_Loop ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_N$ = 8							; size = 4
_Infinite_Recursion PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 944
	push	ebp
	mov	ebp, esp
; Line 945
	mov	eax, DWORD PTR _N$[ebp]
	push	eax
	call	_Infinite_Recursion
	add	esp, 4
; Line 946
	pop	ebp
	ret	0
_Infinite_Recursion ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Halt_Status$ = -4					; size = 4
_x$ = 8							; size = 4
_D	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 936
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 937
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_H
	add	esp, 8
	mov	DWORD PTR _Halt_Status$[ebp], eax
; Line 938
	cmp	DWORD PTR _Halt_Status$[ebp], 0
	je	SHORT $LN2@D
$HERE$4:
; Line 939
	jmp	SHORT $HERE$4
$LN2@D:
; Line 940
	mov	eax, DWORD PTR _Halt_Status$[ebp]
; Line 941
	mov	esp, ebp
	pop	ebp
	ret	0
_D	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Halt_Status$ = -4					; size = 4
_x$ = 8							; size = 4
_DD	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 928
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 929
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_HH
	add	esp, 8
	mov	DWORD PTR _Halt_Status$[ebp], eax
; Line 930
	cmp	DWORD PTR _Halt_Status$[ebp], 0
	je	SHORT $LN2@DD
$HERE$4:
; Line 931
	jmp	SHORT $HERE$4
$LN2@DD:
; Line 932
	mov	eax, 1
; Line 933
	mov	esp, ebp
	pop	ebp
	ret	0
_DD	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_E	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 923
	push	ebp
	mov	ebp, esp
; Line 924
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_H
	add	esp, 8
; Line 925
	pop	ebp
	ret	0
_E	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Halt_Status$ = -4					; size = 4
_x$ = 8							; size = 4
_P	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 915
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 916
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_H
	add	esp, 8
	mov	DWORD PTR _Halt_Status$[ebp], eax
; Line 917
	cmp	DWORD PTR _Halt_Status$[ebp], 0
	je	SHORT $LN1@P
$HERE$4:
; Line 918
	jmp	SHORT $HERE$4
$LN1@P:
; Line 920
	mov	esp, ebp
	pop	ebp
	ret	0
_P	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Halt_Status$ = -4					; size = 4
_x$ = 8							; size = 4
_PP	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 907
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 908
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_HH
	add	esp, 8
	mov	DWORD PTR _Halt_Status$[ebp], eax
; Line 909
	cmp	DWORD PTR _Halt_Status$[ebp], 0
	je	SHORT $LN1@PP
$HERE$4:
; Line 910
	jmp	SHORT $HERE$4
$LN1@PP:
; Line 912
	mov	esp, ebp
	pop	ebp
	ret	0
_PP	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_Kozen_N PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 900
	push	ebp
	mov	ebp, esp
; Line 901
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_Kozen_K
	add	esp, 8
	test	eax, eax
	je	SHORT $LN2@Kozen_N
$HERE$4:
; Line 902
	jmp	SHORT $HERE$4
$LN2@Kozen_N:
; Line 903
	mov	eax, 1
; Line 904
	pop	ebp
	ret	0
_Kozen_N ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Strachey_P PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 894
	push	ebp
	mov	ebp, esp
$L$4:
; Line 895
	push	OFFSET _Strachey_P
	call	_T
	add	esp, 4
	test	eax, eax
	je	SHORT $LN1@Strachey_P
	jmp	SHORT $L$4
$LN1@Strachey_P:
; Line 897
	pop	ebp
	ret	0
_Strachey_P ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_M$ = 8							; size = 4
_Sipser_D PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 883
	push	ebp
	mov	ebp, esp
; Line 884
	mov	eax, DWORD PTR _M$[ebp]
	push	eax
	mov	ecx, DWORD PTR _M$[ebp]
	push	ecx
	call	_Sipser_H
	add	esp, 8
	test	eax, eax
	je	SHORT $LN2@Sipser_D
; Line 885
	xor	eax, eax
	jmp	SHORT $LN1@Sipser_D
$LN2@Sipser_D:
; Line 886
	mov	eax, 1
$LN1@Sipser_D:
; Line 887
	pop	ebp
	ret	0
_Sipser_D ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_Px	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 861
	push	ebp
	mov	ebp, esp
; Line 862
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_H
	add	esp, 8
; Line 864
	pop	ebp
	ret	0
_Px	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_Pz	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 856
	push	ebp
	mov	ebp, esp
; Line 857
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_Simulate
	add	esp, 8
; Line 858
	pop	ebp
	ret	0
_Pz	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Halt_Status$ = -4					; size = 4
_x$ = 8							; size = 4
_Py	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 848
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 849
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_Simulate
	add	esp, 8
	mov	DWORD PTR _Halt_Status$[ebp], eax
; Line 850
	cmp	DWORD PTR _Halt_Status$[ebp], 0
	je	SHORT $LN1@Py
$HERE$4:
; Line 851
	jmp	SHORT $HERE$4
$LN1@Py:
; Line 853
	mov	esp, ebp
	pop	ebp
	ret	0
_Py	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_y$ = 12						; size = 4
_Simulate PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 841
	push	ebp
	mov	ebp, esp
; Line 842
	mov	eax, DWORD PTR _y$[ebp]
	push	eax
	call	DWORD PTR _x$[ebp]
	add	esp, 4
; Line 843
	mov	eax, 1
; Line 844
	pop	ebp
	ret	0
_Simulate ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_PR	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 824
	push	ebp
	mov	ebp, esp
; Line 825
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	call	_HR
	add	esp, 4
; Line 826
	pop	ebp
	ret	0
_PR	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_y$ = 8							; size = 4
_HR	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 829
	push	ebp
	mov	ebp, esp
; Line 830
	mov	eax, DWORD PTR _y$[ebp]
	push	eax
	call	_PR
	add	esp, 4
; Line 831
	pop	ebp
	ret	0
_HR	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_Add3	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 817
	push	ebp
	mov	ebp, esp
; Line 818
	mov	eax, DWORD PTR _x$[ebp]
	add	eax, 3
; Line 819
	pop	ebp
	ret	0
_Add3	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Infinite_Loop3 PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 809
	push	ebp
	mov	ebp, esp
$L1$3:
; Line 810
	jmp	SHORT $L3$4
$L2$5:
; Line 811
	jmp	SHORT $L4$6
$L3$4:
; Line 812
	jmp	SHORT $L2$5
$L4$6:
; Line 814
	pop	ebp
	ret	0
_Infinite_Loop3 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Infinite_Loop2 PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 803
	push	ebp
	mov	ebp, esp
$L1$3:
; Line 804
	jmp	SHORT $L3$4
$L2$5:
; Line 805
	jmp	SHORT $L1$3
$L3$4:
; Line 806
	jmp	SHORT $L2$5
; Line 807
	pop	ebp
	ret	0
_Infinite_Loop2 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_P$ = 8							; size = 4
_I$ = 12						; size = 4
_Halts	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 798
	push	ebp
	mov	ebp, esp
; Line 799
	xor	eax, eax
; Line 800
	pop	ebp
	ret	0
_Halts	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_decoded$ = -32						; size = 4
_code_end$ = -28					; size = 4
_master_state$ = -24					; size = 4
_End_Of_Code$ = -20					; size = 4
_execution_trace$ = -16					; size = 4
_slave_state$ = -12					; size = 4
_slave_stack$ = -8					; size = 4
_Address_of_T$ = -4					; size = 4
_P$ = 8							; size = 4
_T	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 771
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
; Line 772
	push	OFFSET _T
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _End_Of_Code$[ebp], eax
; Line 773
	mov	DWORD PTR _Address_of_T$[ebp], OFFSET _T
; Line 774
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _code_end$[ebp], eax
; Line 775
	push	24					; 00000018H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _decoded$[ebp], eax
; Line 777
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _master_state$[ebp], eax
; Line 778
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_state$[ebp], eax
; Line 779
	push	65536					; 00010000H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_stack$[ebp], eax
; Line 780
	push	24000					; 00005dc0H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _execution_trace$[ebp], eax
; Line 781
	mov	ecx, DWORD PTR _slave_stack$[ebp]
	push	ecx
	mov	edx, DWORD PTR _slave_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _End_Of_Code$[ebp]
	push	eax
	mov	ecx, DWORD PTR _P$[ebp]
	push	ecx
	call	_Init_slave_state0
	add	esp, 16					; 00000010H
; Line 782
	mov	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	push	OFFSET $SG10008
	call	_Output
	add	esp, 8
; Line 783
	mov	eax, DWORD PTR _Address_of_T$[ebp]
	push	eax
	push	OFFSET $SG10009
	call	_Output
	add	esp, 8
; Line 784
	mov	ecx, DWORD PTR _P$[ebp]
	push	ecx
	mov	edx, DWORD PTR _Address_of_T$[ebp]
	push	edx
	lea	eax, DWORD PTR _slave_stack$[ebp]
	push	eax
	lea	ecx, DWORD PTR _slave_state$[ebp]
	push	ecx
	lea	edx, DWORD PTR _master_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _code_end$[ebp]
	push	eax
	lea	ecx, DWORD PTR _decoded$[ebp]
	push	ecx
	lea	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	push	OFFSET $SG10011
	call	_Decide_Halting0
	add	esp, 36					; 00000024H
	test	eax, eax
	je	SHORT $LN2@T
; Line 786
	jmp	SHORT $END_OF_CODE$4
$LN2@T:
; Line 787
	xor	eax, eax
	jmp	SHORT $LN1@T
$END_OF_CODE$4:
; Line 789
	push	OFFSET $SG10012
	call	_OutputString
	add	esp, 4
; Line 790
	mov	eax, 1
$LN1@T:
; Line 791
	mov	esp, ebp
	pop	ebp
	ret	0
_T	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_decoded$ = -32						; size = 4
_code_end$ = -28					; size = 4
_master_state$ = -24					; size = 4
_End_Of_Code$ = -20					; size = 4
_execution_trace$ = -16					; size = 4
_slave_state$ = -12					; size = 4
_slave_stack$ = -8					; size = 4
_Address_of_H0$ = -4					; size = 4
_P$ = 8							; size = 4
_H0	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 747
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
; Line 748
	push	OFFSET _H0
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _End_Of_Code$[ebp], eax
; Line 749
	mov	DWORD PTR _Address_of_H0$[ebp], OFFSET _H0
; Line 750
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _code_end$[ebp], eax
; Line 751
	push	24					; 00000018H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _decoded$[ebp], eax
; Line 753
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _master_state$[ebp], eax
; Line 754
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_state$[ebp], eax
; Line 755
	push	65536					; 00010000H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_stack$[ebp], eax
; Line 756
	push	24000					; 00005dc0H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _execution_trace$[ebp], eax
; Line 757
	mov	ecx, DWORD PTR _slave_stack$[ebp]
	push	ecx
	mov	edx, DWORD PTR _slave_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _End_Of_Code$[ebp]
	push	eax
	mov	ecx, DWORD PTR _P$[ebp]
	push	ecx
	call	_Init_slave_state0
	add	esp, 16					; 00000010H
; Line 758
	mov	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	push	OFFSET $SG9977
	call	_Output
	add	esp, 8
; Line 759
	mov	eax, DWORD PTR _Address_of_H0$[ebp]
	push	eax
	push	OFFSET $SG9978
	call	_Output
	add	esp, 8
; Line 760
	mov	ecx, DWORD PTR _P$[ebp]
	push	ecx
	mov	edx, DWORD PTR _Address_of_H0$[ebp]
	push	edx
	lea	eax, DWORD PTR _slave_stack$[ebp]
	push	eax
	lea	ecx, DWORD PTR _slave_state$[ebp]
	push	ecx
	lea	edx, DWORD PTR _master_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _code_end$[ebp]
	push	eax
	lea	ecx, DWORD PTR _decoded$[ebp]
	push	ecx
	lea	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	push	OFFSET $SG9980
	call	_Decide_Halting0
	add	esp, 36					; 00000024H
	test	eax, eax
	je	SHORT $LN2@H0
; Line 762
	jmp	SHORT $END_OF_CODE$4
$LN2@H0:
; Line 763
	xor	eax, eax
	jmp	SHORT $LN1@H0
$END_OF_CODE$4:
; Line 765
	push	OFFSET $SG9981
	call	_OutputString
	add	esp, 4
; Line 766
	mov	eax, 1
$LN1@H0:
; Line 767
	mov	esp, ebp
	pop	ebp
	ret	0
_H0	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_decoded$ = -32						; size = 4
_code_end$ = -28					; size = 4
_master_state$ = -24					; size = 4
_End_Of_Code$ = -20					; size = 4
_execution_trace$ = -16					; size = 4
_slave_state$ = -12					; size = 4
_slave_stack$ = -8					; size = 4
_Address_of_Kozen_K$ = -4				; size = 4
_P$ = 8							; size = 4
_I$ = 12						; size = 4
_Kozen_K PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 721
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
; Line 722
	push	OFFSET _H
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _End_Of_Code$[ebp], eax
; Line 723
	mov	DWORD PTR _Address_of_Kozen_K$[ebp], OFFSET _Kozen_K
; Line 724
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _code_end$[ebp], eax
; Line 725
	push	24					; 00000018H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _decoded$[ebp], eax
; Line 727
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _master_state$[ebp], eax
; Line 728
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_state$[ebp], eax
; Line 729
	push	65536					; 00010000H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_stack$[ebp], eax
; Line 730
	push	240000					; 0003a980H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _execution_trace$[ebp], eax
; Line 733
	mov	ecx, DWORD PTR _slave_stack$[ebp]
	push	ecx
	mov	edx, DWORD PTR _slave_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _End_Of_Code$[ebp]
	push	eax
	mov	ecx, DWORD PTR _I$[ebp]
	push	ecx
	mov	edx, DWORD PTR _P$[ebp]
	push	edx
	call	_Init_slave_state
	add	esp, 20					; 00000014H
; Line 734
	mov	eax, DWORD PTR _execution_trace$[ebp]
	push	eax
	push	OFFSET $SG9946
	call	_Output
	add	esp, 8
; Line 735
	mov	ecx, DWORD PTR _Address_of_Kozen_K$[ebp]
	push	ecx
	push	OFFSET $SG9947
	call	_Output
	add	esp, 8
; Line 736
	mov	edx, DWORD PTR _I$[ebp]
	push	edx
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Address_of_Kozen_K$[ebp]
	push	ecx
	lea	edx, DWORD PTR _slave_stack$[ebp]
	push	edx
	lea	eax, DWORD PTR _slave_state$[ebp]
	push	eax
	lea	ecx, DWORD PTR _master_state$[ebp]
	push	ecx
	mov	edx, DWORD PTR _code_end$[ebp]
	push	edx
	lea	eax, DWORD PTR _decoded$[ebp]
	push	eax
	lea	ecx, DWORD PTR _execution_trace$[ebp]
	push	ecx
	push	OFFSET $SG9949
	call	_Decide_Halting
	add	esp, 40					; 00000028H
	test	eax, eax
	je	SHORT $LN2@Kozen_K
; Line 739
	push	OFFSET $SG9950
	call	_OutputString
	add	esp, 4
; Line 740
	mov	eax, 1
	jmp	SHORT $LN1@Kozen_K
$LN2@Kozen_K:
; Line 742
	xor	eax, eax
$LN1@Kozen_K:
; Line 743
	mov	esp, ebp
	pop	ebp
	ret	0
_Kozen_K ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_decoded$ = -32						; size = 4
_code_end$ = -28					; size = 4
_master_state$ = -24					; size = 4
_End_Of_Code$ = -20					; size = 4
_execution_trace$ = -16					; size = 4
_slave_state$ = -12					; size = 4
_slave_stack$ = -8					; size = 4
_Address_of_Sipser_H$ = -4				; size = 4
_P$ = 8							; size = 4
_I$ = 12						; size = 4
_Sipser_H PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 695
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
; Line 696
	push	OFFSET _H
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _End_Of_Code$[ebp], eax
; Line 697
	mov	DWORD PTR _Address_of_Sipser_H$[ebp], OFFSET _Sipser_H
; Line 698
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _code_end$[ebp], eax
; Line 699
	push	24					; 00000018H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _decoded$[ebp], eax
; Line 701
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _master_state$[ebp], eax
; Line 702
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_state$[ebp], eax
; Line 703
	push	65536					; 00010000H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_stack$[ebp], eax
; Line 704
	push	240000					; 0003a980H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _execution_trace$[ebp], eax
; Line 707
	mov	ecx, DWORD PTR _slave_stack$[ebp]
	push	ecx
	mov	edx, DWORD PTR _slave_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _End_Of_Code$[ebp]
	push	eax
	mov	ecx, DWORD PTR _I$[ebp]
	push	ecx
	mov	edx, DWORD PTR _P$[ebp]
	push	edx
	call	_Init_slave_state
	add	esp, 20					; 00000014H
; Line 708
	mov	eax, DWORD PTR _execution_trace$[ebp]
	push	eax
	push	OFFSET $SG9908
	call	_Output
	add	esp, 8
; Line 709
	mov	ecx, DWORD PTR _Address_of_Sipser_H$[ebp]
	push	ecx
	push	OFFSET $SG9909
	call	_Output
	add	esp, 8
; Line 710
	mov	edx, DWORD PTR _I$[ebp]
	push	edx
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Address_of_Sipser_H$[ebp]
	push	ecx
	lea	edx, DWORD PTR _slave_stack$[ebp]
	push	edx
	lea	eax, DWORD PTR _slave_state$[ebp]
	push	eax
	lea	ecx, DWORD PTR _master_state$[ebp]
	push	ecx
	mov	edx, DWORD PTR _code_end$[ebp]
	push	edx
	lea	eax, DWORD PTR _decoded$[ebp]
	push	eax
	lea	ecx, DWORD PTR _execution_trace$[ebp]
	push	ecx
	push	OFFSET $SG9911
	call	_Decide_Halting
	add	esp, 40					; 00000028H
	test	eax, eax
	je	SHORT $LN2@Sipser_H
; Line 713
	push	OFFSET $SG9912
	call	_OutputString
	add	esp, 4
; Line 714
	mov	eax, 1
	jmp	SHORT $LN1@Sipser_H
$LN2@Sipser_H:
; Line 716
	xor	eax, eax
$LN1@Sipser_H:
; Line 717
	mov	esp, ebp
	pop	ebp
	ret	0
_Sipser_H ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_decoded$ = -32						; size = 4
_code_end$ = -28					; size = 4
_master_state$ = -24					; size = 4
_End_Of_Code$ = -20					; size = 4
_execution_trace$ = -16					; size = 4
_slave_state$ = -12					; size = 4
_slave_stack$ = -8					; size = 4
_Address_of_H$ = -4					; size = 4
_P$ = 8							; size = 4
_I$ = 12						; size = 4
_H	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 669
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
; Line 670
	push	OFFSET _H
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _End_Of_Code$[ebp], eax
; Line 671
	mov	DWORD PTR _Address_of_H$[ebp], OFFSET _H
; Line 672
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _code_end$[ebp], eax
; Line 673
	push	24					; 00000018H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _decoded$[ebp], eax
; Line 675
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _master_state$[ebp], eax
; Line 676
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_state$[ebp], eax
; Line 677
	push	65536					; 00010000H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_stack$[ebp], eax
; Line 678
	push	240000					; 0003a980H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _execution_trace$[ebp], eax
; Line 681
	mov	ecx, DWORD PTR _slave_stack$[ebp]
	push	ecx
	mov	edx, DWORD PTR _slave_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _End_Of_Code$[ebp]
	push	eax
	mov	ecx, DWORD PTR _I$[ebp]
	push	ecx
	mov	edx, DWORD PTR _P$[ebp]
	push	edx
	call	_Init_slave_state
	add	esp, 20					; 00000014H
; Line 682
	mov	eax, DWORD PTR _execution_trace$[ebp]
	push	eax
	push	OFFSET $SG9870
	call	_Output
	add	esp, 8
; Line 683
	mov	ecx, DWORD PTR _Address_of_H$[ebp]
	push	ecx
	push	OFFSET $SG9871
	call	_Output
	add	esp, 8
; Line 684
	mov	edx, DWORD PTR _I$[ebp]
	push	edx
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Address_of_H$[ebp]
	push	ecx
	lea	edx, DWORD PTR _slave_stack$[ebp]
	push	edx
	lea	eax, DWORD PTR _slave_state$[ebp]
	push	eax
	lea	ecx, DWORD PTR _master_state$[ebp]
	push	ecx
	mov	edx, DWORD PTR _code_end$[ebp]
	push	edx
	lea	eax, DWORD PTR _decoded$[ebp]
	push	eax
	lea	ecx, DWORD PTR _execution_trace$[ebp]
	push	ecx
	push	OFFSET $SG9873
	call	_Decide_Halting
	add	esp, 40					; 00000028H
	test	eax, eax
	je	SHORT $LN2@H
; Line 687
	push	OFFSET $SG9874
	call	_OutputString
	add	esp, 4
; Line 688
	mov	eax, 1
	jmp	SHORT $LN1@H
$LN2@H:
; Line 690
	xor	eax, eax
$LN1@H:
; Line 691
	mov	esp, ebp
	pop	ebp
	ret	0
_H	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_decoded$ = -32						; size = 4
_code_end$ = -28					; size = 4
_master_state$ = -24					; size = 4
_End_Of_Code$ = -20					; size = 4
_execution_trace$ = -16					; size = 4
_slave_state$ = -12					; size = 4
_slave_stack$ = -8					; size = 4
_Address_of_H1$ = -4					; size = 4
_P$ = 8							; size = 4
_I$ = 12						; size = 4
_H1	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 636
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
; Line 637
	push	OFFSET _H1
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _End_Of_Code$[ebp], eax
; Line 638
	mov	DWORD PTR _Address_of_H1$[ebp], OFFSET _H1
; Line 639
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	call	_get_code_end
	add	esp, 4
	mov	DWORD PTR _code_end$[ebp], eax
; Line 640
	push	24					; 00000018H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _decoded$[ebp], eax
; Line 642
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _master_state$[ebp], eax
; Line 643
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_state$[ebp], eax
; Line 644
	push	65536					; 00010000H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _slave_stack$[ebp], eax
; Line 645
	push	240000					; 0003a980H
	call	_Allocate
	add	esp, 4
	mov	DWORD PTR _execution_trace$[ebp], eax
; Line 647
	mov	ecx, DWORD PTR _slave_stack$[ebp]
	push	ecx
	mov	edx, DWORD PTR _slave_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _End_Of_Code$[ebp]
	push	eax
	mov	ecx, DWORD PTR _I$[ebp]
	push	ecx
	mov	edx, DWORD PTR _P$[ebp]
	push	edx
	call	_Init_slave_state
	add	esp, 20					; 00000014H
; Line 648
	mov	eax, DWORD PTR _execution_trace$[ebp]
	push	eax
	push	OFFSET $SG9832
	call	_Output
	add	esp, 8
; Line 649
	mov	ecx, DWORD PTR _Address_of_H1$[ebp]
	push	ecx
	push	OFFSET $SG9833
	call	_Output
	add	esp, 8
; Line 650
	mov	edx, DWORD PTR _I$[ebp]
	push	edx
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Address_of_H1$[ebp]
	push	ecx
	lea	edx, DWORD PTR _slave_stack$[ebp]
	push	edx
	lea	eax, DWORD PTR _slave_state$[ebp]
	push	eax
	lea	ecx, DWORD PTR _master_state$[ebp]
	push	ecx
	mov	edx, DWORD PTR _code_end$[ebp]
	push	edx
	lea	eax, DWORD PTR _decoded$[ebp]
	push	eax
	lea	ecx, DWORD PTR _execution_trace$[ebp]
	push	ecx
	push	OFFSET $SG9835
	call	_Decide_Halting
	add	esp, 40					; 00000028H
	test	eax, eax
	je	SHORT $LN2@H1
; Line 653
	push	OFFSET $SG9836
	call	_OutputString
	add	esp, 4
; Line 654
	mov	eax, 1
	jmp	SHORT $LN1@H1
$LN2@H1:
; Line 656
	xor	eax, eax
$LN1@H1:
; Line 657
	mov	esp, ebp
	pop	ebp
	ret	0
_H1	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_decoded$ = -36						; size = 4
_code_end$ = -32					; size = 4
_master_state$ = -28					; size = 4
_Root$ = -24						; size = 4
_End_Of_Code$ = -20					; size = 4
_slave_state$ = -16					; size = 4
_slave_stack$ = -12					; size = 4
_execution_trace$ = -8					; size = 4
_Aborted$ = -4						; size = 4
_P$ = 8							; size = 4
_I$ = 12						; size = 4
_HH	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 556
	push	ebp
	mov	ebp, esp
	sub	esp, 36					; 00000024H
; Line 560
	jmp	SHORT $SKIP$4
$DATA1$5:
; Line 564
	npad	1
	npad	1
	npad	1
	npad	1
$DATA2$6:
; Line 577
	npad	1
	npad	1
	npad	1
	npad	1
$SKIP$4:
; Line 590
	lea	eax, OFFSET $DATA1$5
	mov	DWORD PTR _Aborted$[ebp], eax
	lea	eax, OFFSET $DATA2$6
	mov	DWORD PTR _execution_trace$[ebp], eax
	mov	eax, OFFSET $END_OF_CODE$7
	mov	DWORD PTR _End_Of_Code$[ebp], eax
; Line 611
	lea	eax, DWORD PTR _slave_stack$[ebp]
	push	eax
	lea	ecx, DWORD PTR _slave_state$[ebp]
	push	ecx
	lea	edx, DWORD PTR _master_state$[ebp]
	push	edx
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	lea	ecx, DWORD PTR _code_end$[ebp]
	push	ecx
	lea	edx, DWORD PTR _decoded$[ebp]
	push	edx
	lea	eax, DWORD PTR _execution_trace$[ebp]
	push	eax
	lea	ecx, DWORD PTR _Aborted$[ebp]
	push	ecx
	call	_Init_Halts_HH
	add	esp, 32					; 00000020H
	mov	DWORD PTR _Root$[ebp], eax
; Line 615
	mov	edx, DWORD PTR _slave_stack$[ebp]
	push	edx
	mov	eax, DWORD PTR _slave_state$[ebp]
	push	eax
	mov	ecx, DWORD PTR _End_Of_Code$[ebp]
	push	ecx
	mov	edx, DWORD PTR _I$[ebp]
	push	edx
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	call	_Init_slave_state
	add	esp, 20					; 00000014H
; Line 617
	mov	ecx, DWORD PTR _Root$[ebp]
	push	ecx
	lea	edx, DWORD PTR _slave_stack$[ebp]
	push	edx
	lea	eax, DWORD PTR _slave_state$[ebp]
	push	eax
	lea	ecx, DWORD PTR _master_state$[ebp]
	push	ecx
	mov	edx, DWORD PTR _End_Of_Code$[ebp]
	push	edx
	mov	eax, DWORD PTR _code_end$[ebp]
	push	eax
	lea	ecx, DWORD PTR _decoded$[ebp]
	push	ecx
	lea	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	lea	eax, DWORD PTR _Aborted$[ebp]
	push	eax
	call	_Decide_Halting_HH
	add	esp, 36					; 00000024H
	test	eax, eax
	je	SHORT $LN2@HH
; Line 620
	jmp	SHORT $END_OF_CODE$7
$LN2@HH:
; Line 622
	mov	ecx, DWORD PTR _Aborted$[ebp]
	mov	DWORD PTR [ecx], -1869574000		; 90909090H
; Line 623
	mov	edx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR [edx], -1869574000		; 90909090H
; Line 624
	xor	eax, eax
	jmp	SHORT $LN1@HH
$END_OF_CODE$7:
; Line 627
	mov	eax, DWORD PTR _Aborted$[ebp]
	mov	DWORD PTR [eax], -1869574000		; 90909090H
; Line 628
	mov	ecx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR [ecx], -1869574000		; 90909090H
; Line 629
	mov	eax, 1
$LN1@HH:
; Line 630
	mov	esp, ebp
	pop	ebp
	ret	0
_HH	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Aborted$ = 8						; size = 4
_execution_trace$ = 12					; size = 4
_decoded$ = 16						; size = 4
_code_end$ = 20						; size = 4
_P$ = 24						; size = 4
_master_state$ = 28					; size = 4
_slave_state$ = 32					; size = 4
_slave_stack$ = 36					; size = 4
_Init_Halts_HH PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 529
	push	ebp
	mov	ebp, esp
; Line 530
	push	24					; 00000018H
	call	_Allocate
	add	esp, 4
	mov	ecx, DWORD PTR _decoded$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 531
	mov	edx, DWORD PTR _P$[ebp]
	push	edx
	call	_get_code_end
	add	esp, 4
	mov	ecx, DWORD PTR _code_end$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 532
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	edx, DWORD PTR _master_state$[ebp]
	mov	DWORD PTR [edx], eax
; Line 533
	push	52					; 00000034H
	call	_Allocate
	add	esp, 4
	mov	ecx, DWORD PTR _slave_state$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 534
	push	65536					; 00010000H
	call	_Allocate
	add	esp, 4
	mov	edx, DWORD PTR _slave_stack$[ebp]
	mov	DWORD PTR [edx], eax
; Line 535
	mov	eax, DWORD PTR _slave_stack$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	push	OFFSET $SG9773
	call	_Output
	add	esp, 8
; Line 536
	mov	edx, DWORD PTR _execution_trace$[ebp]
	mov	eax, DWORD PTR [edx]
	cmp	DWORD PTR [eax], -1869574000		; 90909090H
	jne	SHORT $LN2@Init_Halts
; Line 539
	mov	ecx, DWORD PTR _Aborted$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR [edx], 0
; Line 540
	push	240000					; 0003a980H
	call	_Allocate
	add	esp, 4
	mov	ecx, DWORD PTR _execution_trace$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR [edx], eax
; Line 541
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	edx
	push	OFFSET $SG9775
	call	_Output
	add	esp, 8
; Line 543
	mov	eax, 1
	jmp	SHORT $LN1@Init_Halts
$LN2@Init_Halts:
; Line 545
	xor	eax, eax
$LN1@Init_Halts:
; Line 546
	pop	ebp
	ret	0
_Init_Halts_HH ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_address$1 = -16					; size = 4
_Current_Length_Of_Execution_Trace$ = -12		; size = 4
_size$2 = -8						; size = 4
_EIP$3 = -4						; size = 4
_Aborted$ = 8						; size = 4
_execution_trace$ = 12					; size = 4
_decoded$ = 16						; size = 4
_code_end$ = 20						; size = 4
_End_Of_Code$ = 24					; size = 4
_master_state$ = 28					; size = 4
_slave_state$ = 32					; size = 4
_slave_stack$ = 36					; size = 4
_Root$ = 40						; size = 4
_Decide_Halting_HH PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 483
	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
; Line 484
	mov	DWORD PTR _Current_Length_Of_Execution_Trace$[ebp], 0
$LN2@Decide_Hal:
; Line 485
	mov	eax, DWORD PTR _Aborted$[ebp]
	mov	ecx, DWORD PTR [eax]
	cmp	DWORD PTR [ecx], 0
	jne	$LN3@Decide_Hal
; Line 487
	mov	edx, DWORD PTR _slave_state$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _EIP$3[ebp], ecx
; Line 488
	mov	edx, DWORD PTR _decoded$[ebp]
	mov	eax, DWORD PTR [edx]
	push	eax
	mov	ecx, DWORD PTR _slave_state$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	mov	eax, DWORD PTR _master_state$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	call	_DebugStep
	add	esp, 12					; 0000000cH
; Line 492
	call	_Last_Address_Of_Operating_System
	cmp	DWORD PTR _EIP$3[ebp], eax
	jbe	SHORT $LN4@Decide_Hal
; Line 494
	push	24					; 00000018H
	mov	edx, DWORD PTR _decoded$[ebp]
	mov	eax, DWORD PTR [edx]
	push	eax
	mov	ecx, DWORD PTR _execution_trace$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	eax, DWORD PTR [edx]
	push	eax
	call	_PushBack
	add	esp, 12					; 0000000cH
$LN4@Decide_Hal:
; Line 498
	mov	ecx, DWORD PTR _EIP$3[ebp]
	cmp	ecx, DWORD PTR _code_end$[ebp]
	jne	SHORT $LN5@Decide_Hal
; Line 499
	mov	eax, 1
	jmp	SHORT $LN1@Decide_Hal
$LN5@Decide_Hal:
; Line 501
	cmp	DWORD PTR _Root$[ebp], 0
	je	SHORT $LN6@Decide_Hal
; Line 503
	mov	edx, DWORD PTR _execution_trace$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _address$1[ebp], ecx
; Line 504
	mov	edx, DWORD PTR _address$1[ebp]
	mov	eax, DWORD PTR [edx-4]
	mov	DWORD PTR _size$2[ebp], eax
; Line 507
	mov	ecx, DWORD PTR _size$2[ebp]
	cmp	ecx, DWORD PTR _Current_Length_Of_Execution_Trace$[ebp]
	jbe	SHORT $LN6@Decide_Hal
; Line 509
	mov	edx, DWORD PTR _size$2[ebp]
	mov	DWORD PTR _Current_Length_Of_Execution_Trace$[ebp], edx
; Line 510
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	edx
	call	_Needs_To_Be_Aborted_HH
	add	esp, 4
	mov	ecx, DWORD PTR _Aborted$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR [edx], eax
$LN6@Decide_Hal:
; Line 514
	jmp	$LN2@Decide_Hal
$LN3@Decide_Hal:
; Line 515
	mov	eax, DWORD PTR _Aborted$[ebp]
	mov	ecx, DWORD PTR [eax]
	cmp	DWORD PTR [ecx], 1
	jne	SHORT $LN8@Decide_Hal
; Line 516
	xor	eax, eax
	jmp	SHORT $LN1@Decide_Hal
$LN8@Decide_Hal:
; Line 517
	mov	eax, 1
$LN1@Decide_Hal:
; Line 518
	mov	esp, ebp
	pop	ebp
	ret	0
_Decide_Halting_HH ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_last$ = -20						; size = 4
_size$ = -16						; size = 4
_ptr$ = -12						; size = 4
_Aborted$ = -8						; size = 4
_current$ = -4						; size = 4
_execution_trace$ = 8					; size = 4
_Needs_To_Be_Aborted_HH PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 456
	push	ebp
	mov	ebp, esp
	sub	esp, 20					; 00000014H
; Line 457
	mov	DWORD PTR _Aborted$[ebp], 0
; Line 458
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _ptr$[ebp], eax
; Line 459
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _ptr$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _size$[ebp], ecx
; Line 462
	mov	eax, DWORD PTR _size$[ebp]
	xor	edx, edx
	mov	ecx, 24					; 00000018H
	div	ecx
	sub	eax, 1
	mov	DWORD PTR _last$[ebp], eax
; Line 463
	imul	edx, DWORD PTR _last$[ebp], 24
	add	edx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _current$[ebp], edx
; Line 465
	mov	eax, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [eax+16], 232			; 000000e8H
	jne	SHORT $LN2@Needs_To_B
; Line 466
	mov	ecx, DWORD PTR _current$[ebp]
	push	ecx
	mov	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	call	_Needs_To_Be_Aborted_Trace_HH
	add	esp, 8
	mov	DWORD PTR _Aborted$[ebp], eax
	jmp	SHORT $LN3@Needs_To_B
$LN2@Needs_To_B:
; Line 467
	mov	eax, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [eax+16], 235			; 000000ebH
	jne	SHORT $LN3@Needs_To_B
; Line 468
	mov	ecx, DWORD PTR _current$[ebp]
	push	ecx
	mov	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	call	_Needs_To_Be_Aborted_Trace_HH
	add	esp, 8
	mov	DWORD PTR _Aborted$[ebp], eax
$LN3@Needs_To_B:
; Line 469
	mov	eax, DWORD PTR _Aborted$[ebp]
; Line 470
	mov	esp, ebp
	pop	ebp
	ret	0
_Needs_To_Be_Aborted_HH ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_next2last$ = -24					; size = 4
_size$ = -20						; size = 4
_ptr$ = -16						; size = 4
_Count_Conditional_Branch_Instructions$ = -12		; size = 4
_N$ = -8						; size = 4
_traced$ = -4						; size = 4
_execution_trace$ = 8					; size = 4
_current$ = 12						; size = 4
_Needs_To_Be_Aborted_Trace_HH PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 409
	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
; Line 414
	mov	DWORD PTR _Count_Conditional_Branch_Instructions$[ebp], 0
; Line 416
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _ptr$[ebp], eax
; Line 417
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _ptr$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _size$[ebp], ecx
; Line 419
	mov	eax, DWORD PTR _size$[ebp]
	xor	edx, edx
	mov	ecx, 24					; 00000018H
	div	ecx
	sub	eax, 2
	mov	DWORD PTR _next2last$[ebp], eax
; Line 422
	mov	edx, DWORD PTR _next2last$[ebp]
	mov	DWORD PTR _N$[ebp], edx
	jmp	SHORT $LN4@Needs_To_B
$LN2@Needs_To_B:
	mov	eax, DWORD PTR _N$[ebp]
	sub	eax, 1
	mov	DWORD PTR _N$[ebp], eax
$LN4@Needs_To_B:
	cmp	DWORD PTR _N$[ebp], 0
	jl	$LN3@Needs_To_B
; Line 424
	imul	ecx, DWORD PTR _N$[ebp], 24
	add	ecx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _traced$[ebp], ecx
; Line 427
	mov	edx, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [edx+16], 127			; 0000007fH
	jne	SHORT $LN5@Needs_To_B
; Line 428
	mov	eax, DWORD PTR _Count_Conditional_Branch_Instructions$[ebp]
	add	eax, 1
	mov	DWORD PTR _Count_Conditional_Branch_Instructions$[ebp], eax
$LN5@Needs_To_B:
; Line 430
	mov	ecx, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [ecx+16], 235			; 000000ebH
	jne	SHORT $LN6@Needs_To_B
; Line 431
	mov	edx, DWORD PTR _current$[ebp]
	mov	eax, DWORD PTR _current$[ebp]
	mov	ecx, DWORD PTR [edx+20]
	cmp	ecx, DWORD PTR [eax]
	ja	SHORT $LN6@Needs_To_B
; Line 432
	mov	edx, DWORD PTR _traced$[ebp]
	mov	eax, DWORD PTR _current$[ebp]
	mov	ecx, DWORD PTR [edx]
	cmp	ecx, DWORD PTR [eax+20]
	jne	SHORT $LN6@Needs_To_B
; Line 433
	cmp	DWORD PTR _Count_Conditional_Branch_Instructions$[ebp], 0
	jne	SHORT $LN6@Needs_To_B
; Line 435
	push	OFFSET $SG9687
	call	_OutputString
	add	esp, 4
; Line 437
	mov	eax, 1
	jmp	SHORT $LN1@Needs_To_B
$LN6@Needs_To_B:
; Line 439
	mov	edx, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [edx+16], 232			; 000000e8H
	jne	SHORT $LN10@Needs_To_B
; Line 440
	mov	eax, DWORD PTR _current$[ebp]
	mov	ecx, DWORD PTR _traced$[ebp]
	mov	edx, DWORD PTR [eax+16]
	cmp	edx, DWORD PTR [ecx+16]
	jne	SHORT $LN10@Needs_To_B
; Line 441
	mov	eax, DWORD PTR _current$[ebp]
	mov	ecx, DWORD PTR _traced$[ebp]
	mov	edx, DWORD PTR [eax]
	cmp	edx, DWORD PTR [ecx]
	jne	SHORT $LN10@Needs_To_B
; Line 442
	mov	eax, DWORD PTR _current$[ebp]
	mov	ecx, DWORD PTR _traced$[ebp]
	mov	edx, DWORD PTR [eax+20]
	cmp	edx, DWORD PTR [ecx+20]
	jne	SHORT $LN10@Needs_To_B
; Line 443
	cmp	DWORD PTR _Count_Conditional_Branch_Instructions$[ebp], 0
	jne	SHORT $LN10@Needs_To_B
; Line 445
	push	OFFSET $SG9693
	call	_OutputString
	add	esp, 4
; Line 448
	mov	eax, 1
	jmp	SHORT $LN1@Needs_To_B
$LN10@Needs_To_B:
; Line 450
	jmp	$LN2@Needs_To_B
$LN3@Needs_To_B:
; Line 451
	xor	eax, eax
$LN1@Needs_To_B:
; Line 452
	mov	esp, ebp
	pop	ebp
	ret	0
_Needs_To_Be_Aborted_Trace_HH ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Top_of_Stack$ = -4					; size = 4
_P$ = 8							; size = 4
_I$ = 12						; size = 4
_End_Of_Code$ = 16					; size = 4
_slave_state$ = 20					; size = 4
_slave_stack$ = 24					; size = 4
_Init_slave_state PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 388
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 393
	mov	eax, DWORD PTR _I$[ebp]
	push	eax
	mov	ecx, DWORD PTR _slave_stack$[ebp]
	push	ecx
	call	_StackPush
	add	esp, 8
	mov	DWORD PTR _Top_of_Stack$[ebp], eax
; Line 394
	mov	edx, DWORD PTR _End_Of_Code$[ebp]
	push	edx
	mov	eax, DWORD PTR _slave_stack$[ebp]
	push	eax
	call	_StackPush
	add	esp, 8
	mov	DWORD PTR _Top_of_Stack$[ebp], eax
; Line 396
	mov	ecx, DWORD PTR _slave_state$[ebp]
	push	ecx
	call	_SaveState
	add	esp, 4
; Line 400
	mov	edx, DWORD PTR _slave_state$[ebp]
	mov	eax, DWORD PTR _P$[ebp]
	mov	DWORD PTR [edx], eax
; Line 401
	mov	ecx, DWORD PTR _slave_state$[ebp]
	mov	edx, DWORD PTR _Top_of_Stack$[ebp]
	mov	DWORD PTR [ecx+32], edx
; Line 402
	mov	eax, DWORD PTR _slave_state$[ebp]
	mov	ecx, DWORD PTR _Top_of_Stack$[ebp]
	mov	DWORD PTR [eax+28], ecx
; Line 403
	mov	esp, ebp
	pop	ebp
	ret	0
_Init_slave_state ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_EIP$1 = -8						; size = 4
_Aborted$ = -4						; size = 4
_Halt_Decider_Name$ = 8					; size = 4
_execution_trace$ = 12					; size = 4
_decoded$ = 16						; size = 4
_code_end$ = 20						; size = 4
_master_state$ = 24					; size = 4
_slave_state$ = 28					; size = 4
_slave_stack$ = 32					; size = 4
_Address_of_H$ = 36					; size = 4
_P$ = 40						; size = 4
_I$ = 44						; size = 4
_Decide_Halting PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 351
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 352
	mov	DWORD PTR _Aborted$[ebp], 0
$LN2@Decide_Hal:
; Line 353
	cmp	DWORD PTR _Aborted$[ebp], 0
	jne	SHORT $LN3@Decide_Hal
; Line 355
	mov	eax, DWORD PTR _slave_state$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _EIP$1[ebp], edx
; Line 356
	mov	eax, DWORD PTR _decoded$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	mov	edx, DWORD PTR _slave_state$[ebp]
	mov	eax, DWORD PTR [edx]
	push	eax
	mov	ecx, DWORD PTR _master_state$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	call	_DebugStep
	add	esp, 12					; 0000000cH
; Line 357
	mov	eax, DWORD PTR _EIP$1[ebp]
	cmp	eax, DWORD PTR _code_end$[ebp]
	jne	SHORT $LN4@Decide_Hal
; Line 358
	mov	eax, 1
	jmp	$LN1@Decide_Hal
$LN4@Decide_Hal:
; Line 365
	push	24					; 00000018H
	mov	ecx, DWORD PTR _decoded$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	call	_PushBack
	add	esp, 12					; 0000000cH
; Line 366
	mov	edx, DWORD PTR _I$[ebp]
	push	edx
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Address_of_H$[ebp]
	push	ecx
	mov	edx, DWORD PTR _execution_trace$[ebp]
	mov	eax, DWORD PTR [edx]
	push	eax
	call	_Needs_To_Be_Aborted
	add	esp, 16					; 00000010H
	mov	DWORD PTR _Aborted$[ebp], eax
; Line 368
	jmp	SHORT $LN2@Decide_Hal
$LN3@Decide_Hal:
; Line 369
	cmp	DWORD PTR _Aborted$[ebp], 0
	je	SHORT $LN5@Decide_Hal
; Line 371
	mov	ecx, DWORD PTR _Halt_Decider_Name$[ebp]
	push	ecx
	call	_OutputString
	add	esp, 4
; Line 372
	cmp	DWORD PTR _Aborted$[ebp], 1
	jne	SHORT $LN6@Decide_Hal
; Line 373
	push	OFFSET $SG9645
	call	_OutputString
	add	esp, 4
$LN6@Decide_Hal:
; Line 374
	cmp	DWORD PTR _Aborted$[ebp], 2
	jne	SHORT $LN7@Decide_Hal
; Line 375
	push	OFFSET $SG9647
	call	_OutputString
	add	esp, 4
$LN7@Decide_Hal:
; Line 376
	cmp	DWORD PTR _Aborted$[ebp], 3
	jne	SHORT $LN8@Decide_Hal
; Line 377
	push	OFFSET $SG9649
	call	_OutputString
	add	esp, 4
$LN8@Decide_Hal:
; Line 379
	xor	eax, eax
	jmp	SHORT $LN1@Decide_Hal
$LN5@Decide_Hal:
; Line 381
	mov	eax, 1
$LN1@Decide_Hal:
; Line 382
	mov	esp, ebp
	pop	ebp
	ret	0
_Decide_Halting ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_last$ = -20						; size = 4
_size$ = -16						; size = 4
_ptr$ = -12						; size = 4
_Aborted$ = -8						; size = 4
_current$ = -4						; size = 4
_execution_trace$ = 8					; size = 4
_Address_of_H$ = 12					; size = 4
_P$ = 16						; size = 4
_I$ = 20						; size = 4
_Needs_To_Be_Aborted PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 317
	push	ebp
	mov	ebp, esp
	sub	esp, 20					; 00000014H
; Line 318
	mov	DWORD PTR _Aborted$[ebp], 0
; Line 319
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _ptr$[ebp], eax
; Line 320
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _ptr$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _size$[ebp], ecx
; Line 322
	mov	eax, DWORD PTR _size$[ebp]
	xor	edx, edx
	mov	ecx, 24					; 00000018H
	div	ecx
	sub	eax, 1
	mov	DWORD PTR _last$[ebp], eax
; Line 323
	imul	edx, DWORD PTR _last$[ebp], 24
	add	edx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _current$[ebp], edx
; Line 325
	mov	eax, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [eax+16], 232			; 000000e8H
	jne	SHORT $LN2@Needs_To_B
; Line 327
	mov	ecx, DWORD PTR _current$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	cmp	edx, DWORD PTR _Address_of_H$[ebp]
	jne	SHORT $LN4@Needs_To_B
; Line 328
	mov	eax, DWORD PTR _I$[ebp]
	push	eax
	mov	ecx, DWORD PTR _P$[ebp]
	push	ecx
	mov	edx, DWORD PTR _current$[ebp]
	push	edx
	mov	eax, DWORD PTR _execution_trace$[ebp]
	push	eax
	call	_Infinite_Simulation_Needs_To_Be_Aborted_Trace
	add	esp, 16					; 00000010H
	mov	DWORD PTR _Aborted$[ebp], eax
	jmp	SHORT $LN5@Needs_To_B
$LN4@Needs_To_B:
; Line 331
	mov	ecx, DWORD PTR _current$[ebp]
	push	ecx
	mov	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	call	_Infinite_Recursion_Needs_To_Be_Aborted_Trace
	add	esp, 8
	mov	DWORD PTR _Aborted$[ebp], eax
$LN5@Needs_To_B:
; Line 333
	jmp	SHORT $LN3@Needs_To_B
$LN2@Needs_To_B:
; Line 334
	mov	eax, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [eax+16], 235			; 000000ebH
	jne	SHORT $LN3@Needs_To_B
; Line 335
	mov	ecx, DWORD PTR _current$[ebp]
	push	ecx
	mov	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	call	_Infinite_Loop_Needs_To_Be_Aborted_Trace
	add	esp, 8
	mov	DWORD PTR _Aborted$[ebp], eax
$LN3@Needs_To_B:
; Line 336
	mov	eax, DWORD PTR _Aborted$[ebp]
; Line 337
	mov	esp, ebp
	pop	ebp
	ret	0
_Needs_To_Be_Aborted ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_next2last$ = -32					; size = 4
_size$ = -28						; size = 4
_ptr$ = -24						; size = 4
_Conditional_Branch_Count$ = -20			; size = 4
_Count_PUSH_Instructions$ = -16				; size = 4
_N$ = -12						; size = 4
_Num_PUSH_Matched$ = -8					; size = 4
_traced$ = -4						; size = 4
_execution_trace$ = 8					; size = 4
_current$ = 12						; size = 4
_P$ = 16						; size = 4
_I$ = 20						; size = 4
_Infinite_Simulation_Needs_To_Be_Aborted_Trace PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 280
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
; Line 282
	mov	DWORD PTR _Count_PUSH_Instructions$[ebp], 0
; Line 283
	mov	DWORD PTR _Num_PUSH_Matched$[ebp], 0
; Line 284
	mov	DWORD PTR _Conditional_Branch_Count$[ebp], 0
; Line 286
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _ptr$[ebp], eax
; Line 287
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _ptr$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _size$[ebp], ecx
; Line 288
	mov	eax, DWORD PTR _size$[ebp]
	xor	edx, edx
	mov	ecx, 24					; 00000018H
	div	ecx
	sub	eax, 2
	mov	DWORD PTR _next2last$[ebp], eax
; Line 291
	mov	edx, DWORD PTR _next2last$[ebp]
	mov	DWORD PTR _N$[ebp], edx
	jmp	SHORT $LN4@Infinite_S
$LN2@Infinite_S:
	mov	eax, DWORD PTR _N$[ebp]
	sub	eax, 1
	mov	DWORD PTR _N$[ebp], eax
$LN4@Infinite_S:
	cmp	DWORD PTR _N$[ebp], 0
	jl	$LN3@Infinite_S
; Line 293
	imul	ecx, DWORD PTR _N$[ebp], 24
	add	ecx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _traced$[ebp], ecx
; Line 294
	mov	edx, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [edx+16], 127			; 0000007fH
	jne	SHORT $LN5@Infinite_S
; Line 295
	mov	eax, DWORD PTR _Conditional_Branch_Count$[ebp]
	add	eax, 1
	mov	DWORD PTR _Conditional_Branch_Count$[ebp], eax
$LN5@Infinite_S:
; Line 297
	mov	ecx, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [ecx+16], 104			; 00000068H
	jne	SHORT $LN6@Infinite_S
; Line 298
	mov	edx, DWORD PTR _Count_PUSH_Instructions$[ebp]
	add	edx, 1
	mov	DWORD PTR _Count_PUSH_Instructions$[ebp], edx
$LN6@Infinite_S:
; Line 301
	mov	eax, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [eax+16], 104			; 00000068H
	jne	SHORT $LN7@Infinite_S
	mov	ecx, DWORD PTR _traced$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	cmp	edx, DWORD PTR _P$[ebp]
	jne	SHORT $LN7@Infinite_S
	cmp	DWORD PTR _Count_PUSH_Instructions$[ebp], 1
	jne	SHORT $LN7@Infinite_S
; Line 302
	mov	eax, DWORD PTR _Num_PUSH_Matched$[ebp]
	add	eax, 1
	mov	DWORD PTR _Num_PUSH_Matched$[ebp], eax
$LN7@Infinite_S:
; Line 305
	mov	ecx, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [ecx+16], 104			; 00000068H
	jne	SHORT $LN8@Infinite_S
	mov	edx, DWORD PTR _traced$[ebp]
	mov	eax, DWORD PTR [edx+20]
	cmp	eax, DWORD PTR _I$[ebp]
	jne	SHORT $LN8@Infinite_S
	cmp	DWORD PTR _Count_PUSH_Instructions$[ebp], 2
	jne	SHORT $LN8@Infinite_S
; Line 306
	mov	ecx, DWORD PTR _Num_PUSH_Matched$[ebp]
	add	ecx, 1
	mov	DWORD PTR _Num_PUSH_Matched$[ebp], ecx
$LN8@Infinite_S:
; Line 308
	cmp	DWORD PTR _Num_PUSH_Matched$[ebp], 2
	jne	SHORT $LN9@Infinite_S
	cmp	DWORD PTR _N$[ebp], 0
	jne	SHORT $LN9@Infinite_S
	cmp	DWORD PTR _Conditional_Branch_Count$[ebp], 0
	jne	SHORT $LN9@Infinite_S
; Line 309
	mov	eax, 3
	jmp	SHORT $LN1@Infinite_S
$LN9@Infinite_S:
; Line 310
	jmp	$LN2@Infinite_S
$LN3@Infinite_S:
; Line 311
	xor	eax, eax
$LN1@Infinite_S:
; Line 312
	mov	esp, ebp
	pop	ebp
	ret	0
_Infinite_Simulation_Needs_To_Be_Aborted_Trace ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Size$ = -12						; size = 4
_Capacity$ = -8						; size = 4
_Top_of_Stack$ = -4					; size = 4
_P$ = 8							; size = 4
_End_Of_Code$ = 12					; size = 4
_slave_state$ = 16					; size = 4
_slave_stack$ = 20					; size = 4
_Init_slave_state0 PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 261
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 266
	mov	eax, DWORD PTR _End_Of_Code$[ebp]
	push	eax
	mov	ecx, DWORD PTR _slave_stack$[ebp]
	push	ecx
	call	_StackPush
	add	esp, 8
	mov	DWORD PTR _Top_of_Stack$[ebp], eax
; Line 267
	mov	edx, DWORD PTR _slave_state$[ebp]
	push	edx
	call	_SaveState
	add	esp, 4
; Line 268
	mov	eax, 4
	imul	ecx, eax, -2
	mov	edx, DWORD PTR _slave_stack$[ebp]
	mov	eax, DWORD PTR [edx+ecx]
	mov	DWORD PTR _Capacity$[ebp], eax
; Line 269
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _slave_stack$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _Size$[ebp], ecx
; Line 271
	mov	edx, DWORD PTR _slave_state$[ebp]
	mov	eax, DWORD PTR _P$[ebp]
	mov	DWORD PTR [edx], eax
; Line 272
	mov	ecx, DWORD PTR _slave_state$[ebp]
	mov	edx, DWORD PTR _Top_of_Stack$[ebp]
	mov	DWORD PTR [ecx+32], edx
; Line 273
	mov	eax, DWORD PTR _slave_state$[ebp]
	mov	ecx, DWORD PTR _Top_of_Stack$[ebp]
	mov	DWORD PTR [eax+28], ecx
; Line 274
	mov	esp, ebp
	pop	ebp
	ret	0
_Init_slave_state0 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_EIP$1 = -8						; size = 4
_Aborted$ = -4						; size = 4
_Halt_Decider_Name$ = 8					; size = 4
_execution_trace$ = 12					; size = 4
_decoded$ = 16						; size = 4
_code_end$ = 20						; size = 4
_master_state$ = 24					; size = 4
_slave_state$ = 28					; size = 4
_slave_stack$ = 32					; size = 4
_Address_of_H$ = 36					; size = 4
_P$ = 40						; size = 4
_Decide_Halting0 PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 228
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 229
	mov	DWORD PTR _Aborted$[ebp], 0
$LN2@Decide_Hal:
; Line 230
	cmp	DWORD PTR _Aborted$[ebp], 0
	jne	SHORT $LN3@Decide_Hal
; Line 232
	mov	eax, DWORD PTR _slave_state$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _EIP$1[ebp], edx
; Line 233
	mov	eax, DWORD PTR _decoded$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	mov	edx, DWORD PTR _slave_state$[ebp]
	mov	eax, DWORD PTR [edx]
	push	eax
	mov	ecx, DWORD PTR _master_state$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	call	_DebugStep
	add	esp, 12					; 0000000cH
; Line 234
	mov	eax, DWORD PTR _EIP$1[ebp]
	cmp	eax, DWORD PTR _code_end$[ebp]
	jne	SHORT $LN4@Decide_Hal
; Line 235
	mov	eax, 1
	jmp	$LN1@Decide_Hal
$LN4@Decide_Hal:
; Line 240
	push	24					; 00000018H
	mov	ecx, DWORD PTR _decoded$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	call	_PushBack
	add	esp, 12					; 0000000cH
; Line 241
	mov	edx, DWORD PTR _P$[ebp]
	push	edx
	mov	eax, DWORD PTR _Address_of_H$[ebp]
	push	eax
	mov	ecx, DWORD PTR _execution_trace$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	call	_Needs_To_Be_Aborted0
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _Aborted$[ebp], eax
; Line 242
	jmp	SHORT $LN2@Decide_Hal
$LN3@Decide_Hal:
; Line 243
	cmp	DWORD PTR _Aborted$[ebp], 0
	je	SHORT $LN5@Decide_Hal
; Line 245
	mov	eax, DWORD PTR _Halt_Decider_Name$[ebp]
	push	eax
	call	_OutputString
	add	esp, 4
; Line 246
	cmp	DWORD PTR _Aborted$[ebp], 1
	jne	SHORT $LN6@Decide_Hal
; Line 247
	push	OFFSET $SG9542
	call	_OutputString
	add	esp, 4
$LN6@Decide_Hal:
; Line 248
	cmp	DWORD PTR _Aborted$[ebp], 2
	jne	SHORT $LN7@Decide_Hal
; Line 249
	push	OFFSET $SG9544
	call	_OutputString
	add	esp, 4
$LN7@Decide_Hal:
; Line 250
	cmp	DWORD PTR _Aborted$[ebp], 3
	jne	SHORT $LN8@Decide_Hal
; Line 251
	push	OFFSET $SG9546
	call	_OutputString
	add	esp, 4
$LN8@Decide_Hal:
; Line 252
	xor	eax, eax
	jmp	SHORT $LN1@Decide_Hal
$LN5@Decide_Hal:
; Line 254
	mov	eax, 1
$LN1@Decide_Hal:
; Line 255
	mov	esp, ebp
	pop	ebp
	ret	0
_Decide_Halting0 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_last$ = -20						; size = 4
_size$ = -16						; size = 4
_ptr$ = -12						; size = 4
_Aborted$ = -8						; size = 4
_current$ = -4						; size = 4
_execution_trace$ = 8					; size = 4
_Address_of_H$ = 12					; size = 4
_P$ = 16						; size = 4
_Needs_To_Be_Aborted0 PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 196
	push	ebp
	mov	ebp, esp
	sub	esp, 20					; 00000014H
; Line 197
	mov	DWORD PTR _Aborted$[ebp], 0
; Line 198
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _ptr$[ebp], eax
; Line 199
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _ptr$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _size$[ebp], ecx
; Line 200
	mov	eax, DWORD PTR _size$[ebp]
	xor	edx, edx
	mov	ecx, 24					; 00000018H
	div	ecx
	sub	eax, 1
	mov	DWORD PTR _last$[ebp], eax
; Line 201
	imul	edx, DWORD PTR _last$[ebp], 24
	add	edx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _current$[ebp], edx
; Line 204
	mov	eax, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [eax+16], 232			; 000000e8H
	jne	SHORT $LN2@Needs_To_B
; Line 206
	mov	ecx, DWORD PTR _current$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	cmp	edx, DWORD PTR _Address_of_H$[ebp]
	jne	SHORT $LN4@Needs_To_B
; Line 207
	mov	eax, DWORD PTR _P$[ebp]
	push	eax
	mov	ecx, DWORD PTR _current$[ebp]
	push	ecx
	mov	edx, DWORD PTR _execution_trace$[ebp]
	push	edx
	call	_Infinite_Simulation_Needs_To_Be_Aborted_Trace0
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _Aborted$[ebp], eax
	jmp	SHORT $LN5@Needs_To_B
$LN4@Needs_To_B:
; Line 209
	mov	eax, DWORD PTR _current$[ebp]
	push	eax
	mov	ecx, DWORD PTR _execution_trace$[ebp]
	push	ecx
	call	_Infinite_Recursion_Needs_To_Be_Aborted_Trace
	add	esp, 8
	mov	DWORD PTR _Aborted$[ebp], eax
$LN5@Needs_To_B:
; Line 210
	jmp	SHORT $LN3@Needs_To_B
$LN2@Needs_To_B:
; Line 211
	mov	edx, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [edx+16], 235			; 000000ebH
	jne	SHORT $LN3@Needs_To_B
; Line 212
	mov	eax, DWORD PTR _current$[ebp]
	push	eax
	mov	ecx, DWORD PTR _execution_trace$[ebp]
	push	ecx
	call	_Infinite_Loop_Needs_To_Be_Aborted_Trace
	add	esp, 8
	mov	DWORD PTR _Aborted$[ebp], eax
$LN3@Needs_To_B:
; Line 213
	mov	eax, DWORD PTR _Aborted$[ebp]
; Line 214
	mov	esp, ebp
	pop	ebp
	ret	0
_Needs_To_Be_Aborted0 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_next2last$ = -32					; size = 4
_size$ = -28						; size = 4
_ptr$ = -24						; size = 4
_Conditional_Branch_Count$ = -20			; size = 4
_Num_PUSH_Matched$ = -16				; size = 4
_Count_PUSH_Instructions$ = -12				; size = 4
_traced$ = -8						; size = 4
_N$1 = -4						; size = 4
_execution_trace$ = 8					; size = 4
_current$ = 12						; size = 4
_P$ = 16						; size = 4
_Infinite_Simulation_Needs_To_Be_Aborted_Trace0 PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 167
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
; Line 169
	mov	DWORD PTR _Count_PUSH_Instructions$[ebp], 0
; Line 170
	mov	DWORD PTR _Num_PUSH_Matched$[ebp], 0
; Line 171
	mov	DWORD PTR _Conditional_Branch_Count$[ebp], 0
; Line 173
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _ptr$[ebp], eax
; Line 174
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _ptr$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _size$[ebp], ecx
; Line 175
	mov	eax, DWORD PTR _size$[ebp]
	xor	edx, edx
	mov	ecx, 24					; 00000018H
	div	ecx
	sub	eax, 2
	mov	DWORD PTR _next2last$[ebp], eax
; Line 176
	mov	edx, DWORD PTR _next2last$[ebp]
	mov	DWORD PTR _N$1[ebp], edx
	jmp	SHORT $LN4@Infinite_S
$LN2@Infinite_S:
	mov	eax, DWORD PTR _N$1[ebp]
	sub	eax, 1
	mov	DWORD PTR _N$1[ebp], eax
$LN4@Infinite_S:
	cmp	DWORD PTR _N$1[ebp], 0
	jl	SHORT $LN3@Infinite_S
; Line 178
	imul	ecx, DWORD PTR _N$1[ebp], 24
	add	ecx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _traced$[ebp], ecx
; Line 179
	mov	edx, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [edx+16], 127			; 0000007fH
	jne	SHORT $LN5@Infinite_S
; Line 180
	mov	eax, DWORD PTR _Conditional_Branch_Count$[ebp]
	add	eax, 1
	mov	DWORD PTR _Conditional_Branch_Count$[ebp], eax
$LN5@Infinite_S:
; Line 182
	mov	ecx, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [ecx+16], 104			; 00000068H
	jne	SHORT $LN6@Infinite_S
; Line 183
	mov	edx, DWORD PTR _Count_PUSH_Instructions$[ebp]
	add	edx, 1
	mov	DWORD PTR _Count_PUSH_Instructions$[ebp], edx
$LN6@Infinite_S:
; Line 185
	mov	eax, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [eax+16], 104			; 00000068H
	jne	SHORT $LN7@Infinite_S
	mov	ecx, DWORD PTR _traced$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	cmp	edx, DWORD PTR _P$[ebp]
	jne	SHORT $LN7@Infinite_S
	cmp	DWORD PTR _Count_PUSH_Instructions$[ebp], 1
	jne	SHORT $LN7@Infinite_S
; Line 186
	mov	eax, DWORD PTR _Num_PUSH_Matched$[ebp]
	add	eax, 1
	mov	DWORD PTR _Num_PUSH_Matched$[ebp], eax
$LN7@Infinite_S:
; Line 188
	cmp	DWORD PTR _Num_PUSH_Matched$[ebp], 1
	jne	SHORT $LN8@Infinite_S
	cmp	DWORD PTR _N$1[ebp], 0
	jne	SHORT $LN8@Infinite_S
	cmp	DWORD PTR _Conditional_Branch_Count$[ebp], 0
	jne	SHORT $LN8@Infinite_S
; Line 189
	mov	eax, 3
	jmp	SHORT $LN1@Infinite_S
$LN8@Infinite_S:
; Line 190
	jmp	SHORT $LN2@Infinite_S
$LN3@Infinite_S:
; Line 191
	xor	eax, eax
$LN1@Infinite_S:
; Line 192
	mov	esp, ebp
	pop	ebp
	ret	0
_Infinite_Simulation_Needs_To_Be_Aborted_Trace0 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_next2last$ = -24					; size = 4
_size$ = -20						; size = 4
_ptr$ = -16						; size = 4
_Conditional_Branch_Count$ = -12			; size = 4
_traced$ = -8						; size = 4
_N$ = -4						; size = 4
_execution_trace$ = 8					; size = 4
_current$ = 12						; size = 4
_Infinite_Recursion_Needs_To_Be_Aborted_Trace PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 138
	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
; Line 140
	mov	DWORD PTR _Conditional_Branch_Count$[ebp], 0
; Line 142
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _ptr$[ebp], eax
; Line 143
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _ptr$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _size$[ebp], ecx
; Line 144
	mov	eax, DWORD PTR _size$[ebp]
	xor	edx, edx
	mov	ecx, 24					; 00000018H
	div	ecx
	sub	eax, 2
	mov	DWORD PTR _next2last$[ebp], eax
; Line 147
	mov	edx, DWORD PTR _next2last$[ebp]
	mov	DWORD PTR _N$[ebp], edx
	jmp	SHORT $LN4@Infinite_R
$LN2@Infinite_R:
	mov	eax, DWORD PTR _N$[ebp]
	sub	eax, 1
	mov	DWORD PTR _N$[ebp], eax
$LN4@Infinite_R:
	cmp	DWORD PTR _N$[ebp], 0
	jl	SHORT $LN3@Infinite_R
; Line 149
	imul	ecx, DWORD PTR _N$[ebp], 24
	add	ecx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _traced$[ebp], ecx
; Line 150
	mov	edx, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [edx+16], 127			; 0000007fH
	jne	SHORT $LN5@Infinite_R
; Line 151
	mov	eax, DWORD PTR _Conditional_Branch_Count$[ebp]
	add	eax, 1
	mov	DWORD PTR _Conditional_Branch_Count$[ebp], eax
$LN5@Infinite_R:
; Line 153
	mov	ecx, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [ecx+16], 232			; 000000e8H
	jne	SHORT $LN6@Infinite_R
; Line 154
	mov	edx, DWORD PTR _current$[ebp]
	mov	eax, DWORD PTR _traced$[ebp]
	mov	ecx, DWORD PTR [edx+16]
	cmp	ecx, DWORD PTR [eax+16]
	jne	SHORT $LN6@Infinite_R
; Line 155
	mov	edx, DWORD PTR _current$[ebp]
	mov	eax, DWORD PTR _traced$[ebp]
	mov	ecx, DWORD PTR [edx]
	cmp	ecx, DWORD PTR [eax]
	jne	SHORT $LN6@Infinite_R
; Line 156
	mov	edx, DWORD PTR _current$[ebp]
	mov	eax, DWORD PTR _traced$[ebp]
	mov	ecx, DWORD PTR [edx+20]
	cmp	ecx, DWORD PTR [eax+20]
	jne	SHORT $LN6@Infinite_R
; Line 157
	cmp	DWORD PTR _Conditional_Branch_Count$[ebp], 0
	jne	SHORT $LN6@Infinite_R
; Line 158
	mov	eax, 2
	jmp	SHORT $LN1@Infinite_R
$LN6@Infinite_R:
; Line 159
	jmp	SHORT $LN2@Infinite_R
$LN3@Infinite_R:
; Line 160
	xor	eax, eax
$LN1@Infinite_R:
; Line 161
	mov	esp, ebp
	pop	ebp
	ret	0
_Infinite_Recursion_Needs_To_Be_Aborted_Trace ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_next2last$ = -24					; size = 4
_size$ = -20						; size = 4
_ptr$ = -16						; size = 4
_traced$ = -12						; size = 4
_Conditional_Branch_Count$ = -8				; size = 4
_N$ = -4						; size = 4
_execution_trace$ = 8					; size = 4
_current$ = 12						; size = 4
_Infinite_Loop_Needs_To_Be_Aborted_Trace PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 112
	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
; Line 114
	mov	DWORD PTR _Conditional_Branch_Count$[ebp], 0
; Line 116
	mov	eax, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _ptr$[ebp], eax
; Line 117
	mov	ecx, 4
	imul	edx, ecx, -1
	mov	eax, DWORD PTR _ptr$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	DWORD PTR _size$[ebp], ecx
; Line 118
	mov	eax, DWORD PTR _size$[ebp]
	xor	edx, edx
	mov	ecx, 24					; 00000018H
	div	ecx
	sub	eax, 2
	mov	DWORD PTR _next2last$[ebp], eax
; Line 121
	mov	edx, DWORD PTR _next2last$[ebp]
	mov	DWORD PTR _N$[ebp], edx
	jmp	SHORT $LN4@Infinite_L
$LN2@Infinite_L:
	mov	eax, DWORD PTR _N$[ebp]
	sub	eax, 1
	mov	DWORD PTR _N$[ebp], eax
$LN4@Infinite_L:
	cmp	DWORD PTR _N$[ebp], 0
	jl	SHORT $LN3@Infinite_L
; Line 123
	imul	ecx, DWORD PTR _N$[ebp], 24
	add	ecx, DWORD PTR _execution_trace$[ebp]
	mov	DWORD PTR _traced$[ebp], ecx
; Line 124
	mov	edx, DWORD PTR _traced$[ebp]
	cmp	DWORD PTR [edx+16], 127			; 0000007fH
	jne	SHORT $LN5@Infinite_L
; Line 125
	mov	eax, DWORD PTR _Conditional_Branch_Count$[ebp]
	add	eax, 1
	mov	DWORD PTR _Conditional_Branch_Count$[ebp], eax
$LN5@Infinite_L:
; Line 127
	mov	ecx, DWORD PTR _current$[ebp]
	cmp	DWORD PTR [ecx+16], 235			; 000000ebH
	jne	SHORT $LN6@Infinite_L
; Line 128
	mov	edx, DWORD PTR _current$[ebp]
	mov	eax, DWORD PTR _current$[ebp]
	mov	ecx, DWORD PTR [edx+20]
	cmp	ecx, DWORD PTR [eax]
	ja	SHORT $LN6@Infinite_L
; Line 129
	mov	edx, DWORD PTR _traced$[ebp]
	mov	eax, DWORD PTR _current$[ebp]
	mov	ecx, DWORD PTR [edx]
	cmp	ecx, DWORD PTR [eax+20]
	jne	SHORT $LN6@Infinite_L
; Line 130
	cmp	DWORD PTR _Conditional_Branch_Count$[ebp], 0
	jne	SHORT $LN6@Infinite_L
; Line 131
	mov	eax, 1
	jmp	SHORT $LN1@Infinite_L
$LN6@Infinite_L:
; Line 132
	jmp	SHORT $LN2@Infinite_L
$LN3@Infinite_L:
; Line 133
	xor	eax, eax
$LN1@Infinite_L:
; Line 134
	mov	esp, ebp
	pop	ebp
	ret	0
_Infinite_Loop_Needs_To_Be_Aborted_Trace ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_size$ = -8						; size = 4
_N$1 = -4						; size = 4
_source$ = 8						; size = 4
_destination$ = 12					; size = 4
_CopyMachineCode PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 94
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 96
	mov	DWORD PTR _size$[ebp], 0
	jmp	SHORT $LN4@CopyMachin
$LN2@CopyMachin:
	mov	eax, DWORD PTR _size$[ebp]
	add	eax, 1
	mov	DWORD PTR _size$[ebp], eax
$LN4@CopyMachin:
	mov	ecx, DWORD PTR _source$[ebp]
	add	ecx, DWORD PTR _size$[ebp]
	movzx	edx, BYTE PTR [ecx]
	cmp	edx, 204				; 000000ccH
	je	SHORT $LN3@CopyMachin
; Line 97
	jmp	SHORT $LN2@CopyMachin
$LN3@CopyMachin:
; Line 98
	mov	eax, DWORD PTR _size$[ebp]
	push	eax
	call	_Allocate
	add	esp, 4
	mov	ecx, DWORD PTR _destination$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 99
	mov	DWORD PTR _N$1[ebp], 0
	jmp	SHORT $LN7@CopyMachin
$LN5@CopyMachin:
	mov	edx, DWORD PTR _N$1[ebp]
	add	edx, 1
	mov	DWORD PTR _N$1[ebp], edx
$LN7@CopyMachin:
	mov	eax, DWORD PTR _N$1[ebp]
	cmp	eax, DWORD PTR _size$[ebp]
	jae	SHORT $LN6@CopyMachin
; Line 101
	mov	ecx, DWORD PTR _source$[ebp]
	add	ecx, DWORD PTR _N$1[ebp]
	movzx	edx, BYTE PTR [ecx]
	push	edx
	push	OFFSET $SG9419
	call	_Output
	add	esp, 8
; Line 102
	mov	eax, DWORD PTR _N$1[ebp]
	mov	ecx, DWORD PTR _destination$[ebp]
	mov	edx, DWORD PTR [ecx+eax*4]
	mov	eax, DWORD PTR _source$[ebp]
	add	eax, DWORD PTR _N$1[ebp]
	mov	cl, BYTE PTR [eax]
	mov	BYTE PTR [edx], cl
; Line 103
	jmp	SHORT $LN5@CopyMachin
$LN6@CopyMachin:
; Line 104
	mov	edx, 4
	imul	eax, edx, -1
	mov	ecx, DWORD PTR _destination$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	ecx, DWORD PTR _size$[ebp]
	mov	DWORD PTR [eax+edx], ecx
; Line 105
	mov	edx, 4
	imul	eax, edx, -1
	mov	ecx, DWORD PTR _destination$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	eax, DWORD PTR [edx+eax]
	push	eax
	push	OFFSET $SG9420
	call	_Output
	add	esp, 8
; Line 106
	mov	ecx, 4
	imul	edx, ecx, -2
	mov	eax, DWORD PTR _destination$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+edx]
	push	edx
	push	OFFSET $SG9421
	call	_Output
	add	esp, 8
; Line 107
	mov	esp, ebp
	pop	ebp
	ret	0
_CopyMachineCode ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_decoded$ = 8						; size = 4
_Output_Decoded PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 89
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_Output_Decoded ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Last_Address_Of_Operating_System PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 88
	push	ebp
	mov	ebp, esp
	xor	eax, eax
	pop	ebp
	ret	0
_Last_Address_Of_Operating_System ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_EIP$ = 8						; size = 4
_get_code_end PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 87
	push	ebp
	mov	ebp, esp
	xor	eax, eax
	pop	ebp
	ret	0
_get_code_end ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_S$ = 8							; size = 4
_M$ = 12						; size = 4
_StackPush PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 86
	push	ebp
	mov	ebp, esp
	xor	eax, eax
	pop	ebp
	ret	0
_StackPush ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_stdvector$ = 8						; size = 4
_data_ptr$ = 12						; size = 4
_size_in_bytes$ = 16					; size = 4
_PushBack PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 85
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_PushBack ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_master_state$ = 8					; size = 4
_slave_state$ = 12					; size = 4
_decoded$ = 16						; size = 4
_DebugStep PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 84
	push	ebp
	mov	ebp, esp
	xor	eax, eax
	pop	ebp
	ret	0
_DebugStep ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_state$ = 8						; size = 4
_LoadState PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 82
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_LoadState ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_state$ = 8						; size = 4
_SaveState PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 81
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_SaveState ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_size$ = 8						; size = 4
_Allocate PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 80
	push	ebp
	mov	ebp, esp
	xor	eax, eax
	pop	ebp
	ret	0
_Allocate ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_S$ = 8							; size = 4
_N$ = 12						; size = 4
_Output	PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 79
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_Output	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_S$ = 8							; size = 4
_OutputString PROC
; File d:\_hp_stream\__nlu_notes\__work_in_progress\__halt_decider_x86\___x86utm_vs\prior_versions\2023_03_02\halt7.c
; Line 78
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_OutputString ENDP
_TEXT	ENDS
END
